version: 2
jobs:
  build:
    working_directory: ~/rollup-plugin-vue
    docker:
      - image: circleci/node:8.5.0
    steps:
      - checkout
      - run:
          name: Install yarn if required
          command: if ! type yarn > /dev/null; then; curl -o- -s -L https://yarnpkg.com/install.sh | bash; fi
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install package dependencies
          command: yarn --no-progress install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Test
          command: npm test
